const countryList = {
  INR: { CNTRY: "IN", CRY: "Indian Rupee" },
  USD: { CNTRY: "US", CRY: "U.S. Dollar" },
  EUR: { CNTRY: "FR", CRY: "European Euro" },
  GBP: { CNTRY: "GB", CRY: "UK Pound Sterling" },
  CHF: { CNTRY: "CH", CRY: "Swiss Franc" },
  AUD: { CNTRY: "AU", CRY: "Australian Dollar" },
  CAD: { CNTRY: "CA", CRY: "Canadian Dollar" },
  SGD: { CNTRY: "SG", CRY: "Singapore Dollar" },
  JPY: { CNTRY: "JP", CRY: "Japanese Yen" },
  CNY: { CNTRY: "CN", CRY: "Chinese Yuan" },
  SAR: { CNTRY: "SA", CRY: "Saudi Arabian Riyal" },
  QAR: { CNTRY: "QA", CRY: "Qatari Riyal" },
  THB: { CNTRY: "TH", CRY: "Thai Baht" },
  AED: { CNTRY: "AE", CRY: "UAE Dirham" },
  MYR: { CNTRY: "MY", CRY: "Malaysian Ringgit" },
  KRW: { CNTRY: "KR", CRY: "South Korean Won" },
  SEK: { CNTRY: "SE", CRY: "Swedish Kroner" },
  DKK: { CNTRY: "DK", CRY: "Danish Kroner" },
  HKD: { CNTRY: "HK", CRY: "Hong Kong Dollar" },
  KWD: { CNTRY: "KW", CRY: "Kuwaity Dinar" },
  BHD: { CNTRY: "BH", CRY: "Bahrain Dinar" },
  NPR: { CNTRY: "NP", CRY: "Nepalese Rupees" },
};
